name: VirusTotal Security Scan

on:
  release:
    types: [published]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          update_release_body: true
          files: |
            debian/pool/main/*.deb
            rpm/*.rpm
        env:
          VT_API_KEY: ${{ secrets.5712b74b994a582490673ac51c77512ed6b3e83fc2896658d91016db932c878d }}
