name: Byte Knight Sponsors Auto-Update

on:
  push:
    branches:
      - main  # Not: Eğer ana dalının adı 'master' ise burayı 'master' yap.
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik çalışır.
  workflow_dispatch:      # Manuel çalıştırma butonu.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Sponsors via GraphQL
        run: |
          curl -H "Authorization: bearer ${{ secrets.SPONSORS_TOKEN }}" \
          -X POST -d '{"query": "query { user(login: \"Neuwj-00\") { sponsors(first: 10) { nodes { ... on User { login avatarUrl url } } } } }"}' \
          https://api.github.com/graphql > sponsor.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "ByteKnightBot"
          git config --global user.email "bot@byteknight.com"
          git add sponsor.json
          # Eğer dosya değişmediyse hata vermemesi için '|| exit 0' ekledik
          git commit -m "chore: update sponsor.json [automated]" || exit 0
          git push
